---
- name: "Check if Golang {{ golang_version }} is installed"
  stat:
    path: "{{ golang_install_dir }}/go-{{ golang_version }}"
  register: s_golang_install_dir

- name: "Download Golang {{ golang_version }}"
  get_url:
    url: "{{ golang_repo }}/{{ golang_install_file }}"
    dest: "/usr/local/src"
  when: not s_golang_install_dir.stat.exists
  
- name: "Create Golang install directory"
  file:
    path: "{{ golang_install_dir }}/go-{{ golang_version }}"
    state: directory
  when: not s_golang_install_dir.stat.exists

- name: "Install Golang {{ golang_version }}"
  unarchive:
    src: "/usr/local/src/{{ golang_install_file }}"
    dest: "{{ golang_install_dir }}/go-{{ golang_version }}"
    extra_opts: [--strip-components=1]
  when: not s_golang_install_dir.stat.exists

- name: "Install golang.sh profiled"
  template:
    src: "golang.sh.j2"
    dest: "/etc/profile.d/golang.sh"
