---
- name: Install linux-dev-playbook
  hosts: localhost
  connection: local
  become: yes

  pre_tasks:
  - name: Update APT-cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"

  roles:
   - default_packages
   - code
   - micro
   - docker
   - kubernetes-tools
   - golang
   - spotify
  
