---
- name: Install Microsoft Visual Studio Code GPG Key for RPM
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present 

- name: Install Microsoft Visual Studio Code DNF Repository
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode
    state: present

- name: Install Microsoft Visual Studio Code
  dnf: 
    name: code
    state: present
