---
- name: Install prerequired packages
  apt:
    name: apt-transport-https
    state: present

- name: Install Microsoft Visual Studio Code GPG Key for APT
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    keyring: "{{ code_keyring }}"
    state: present
    
- name: Install Microsoft Visual Studio Code APT Repository
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by={{ code_keyring }}] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present 
    
- name: Install Microsoft Visual Studio Code
  apt:
    name: code
    state: present
