---
- name: Include tasks for {{ ansible_distribution }}
  include_tasks: "{{ ansible_distribution }}.yml"

- name: "Download Docker-compose {{ docker_compose_version }}"
  get_url:
    url: "{{ docker_compose_repo }}/{{ docker_compose_version }}/{{ docker_compose_install_file }}"
    dest: "/usr/local/src"

- name: "Install docker-compose"
  copy:
    src: "/usr/local/src/{{ docker_compose_install_file }}"
    dest: "/usr/local/bin/docker-compose"
    owner: root
    group: root
    mode: 0755
